"use client";
import Link from "next/link";
import QRCode from "qrcode";
import {useRef,useState} from "react";
import SiteNav from "./site-nav"; import SiteFooter from "./site-footer";
const fmt=(n:number)=>n<1048576?`${Math.max(1,Math.round(n/1024))} KB`:`${(n/1048576).toFixed(1)} MB`;
export default function HomePageClient(){const input=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null);const [drag,setDrag]=useState(false);const [progress,setProgress]=useState<number|null>(null);const [url,setUrl]=useState("");const [qr,setQr]=useState("");
 const choose=(f:File)=>{setFile(f);setUrl("");setProgress(null)};const upload=()=>{if(!file||progress!==null)return;let p=0;setProgress(0);const t=window.setInterval(()=>{p=Math.min(100,p+Math.ceil(Math.random()*10));setProgress(p);if(p===100){clearInterval(t);const u=`https://drop24.app/f/${crypto.randomUUID().slice(0,8)}`;setUrl(u);void QRCode.toDataURL(u,{width:180,margin:1}).then(setQr)}},180)};
 return <div className="flex min-h-screen flex-col bg-background text-foreground"><SiteNav/><main><header className="px-6 pb-16 pt-20"><div className="mx-auto grid max-w-7xl items-end gap-16 lg:grid-cols-2"><div className="animate-entry space-y-8"><h1 className="text-balance text-6xl font-bold uppercase leading-[.9] tracking-tighter md:text-8xl">Files in.<br/><span className="text-primary-bright">Gone in 24.</span></h1><p className="max-w-md text-lg font-medium text-muted-foreground">High-speed file sharing. No ads, no fluff, no permanent storage—just upload, share, and move on.</p><div className="flex flex-wrap gap-3"><button onClick={()=>input.current?.click()} className="industrial-button industrial-button-dark">Drop a File</button><Link href="/pricing" className="industrial-button industrial-button-outline">View Plans</Link></div></div>
 <div role="button" tabIndex={0} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files[0])choose(e.dataTransfer.files[0])}} className={`group animate-entry cursor-pointer border-2 border-dashed bg-card p-10 text-center ${drag?"border-primary-bright bg-secondary":"border-border hover:border-primary-bright"}`}><input ref={input} type="file" className="hidden" onChange={e=>{if(e.target.files?.[0])choose(e.target.files[0]);e.target.value=""}}/><div className="mx-auto flex size-12 items-center justify-center border border-border bg-secondary text-xl group-hover:bg-primary-bright group-hover:text-white">↑</div><h2 className="mt-5 text-2xl font-bold uppercase">{file?file.name:"Drop a file here"}</h2><p className="mt-2 text-sm text-muted-foreground">{file?fmt(file.size):"Choose any file to simulate the original transfer flow."}</p>{progress!==null&&<div className="mx-auto mt-5 h-1.5 max-w-sm bg-secondary"><div className="h-full bg-primary-bright transition-all" style={{width:`${progress}%`}}/></div>}{file&&!url&&<button onClick={e=>{e.stopPropagation();upload()}} className="industrial-button industrial-button-dark mt-6">{progress===null?"Create demo link":`Preparing ${progress}%`}</button>}{url&&<div className="mt-6 border-t border-border pt-5">{qr&&<img src={qr} alt="QR code for simulated link" className="mx-auto size-28 bg-white p-2"/>}<p className="mt-3 break-all font-mono-tight text-xs">{url}</p><button onClick={e=>{e.stopPropagation();void navigator.clipboard?.writeText(url)}} className="industrial-button industrial-button-outline mt-3">Copy link</button></div>}<p className="mt-8 font-mono-tight text-[10px] uppercase tracking-[.16em] text-muted-foreground">Browser-only demo · Nothing is uploaded</p></div></div></header>
 <p className="mx-auto mb-16 max-w-3xl border border-border bg-card px-5 py-4 text-center text-xs text-muted-foreground"><strong className="text-foreground">Portfolio Demo</strong> — Drop24 is no longer operating as a hosted file-transfer service. Files selected here remain entirely on your device.</p>
 <section className="border-y border-border bg-card px-6 py-24"><div className="mx-auto grid max-w-7xl gap-12 sm:grid-cols-2 lg:grid-cols-4">{[["01","Temporal by design","Files self-destruct on schedule. Guest transfers vanish quickly and paid uploads can be extended when needed."],["02","Link or QR, nothing else","Every file gets a direct download URL and a scannable QR. No recipient account required."],["03","No ads, ever","Drop24 carried no advertising and no third-party tracking."],["04","Shared Sessions","Plus and Pro hosts could open a temporary shared locker for group handoffs."]].map(([n,t,c])=><article key={n}><p className="mb-3 font-mono-tight text-xs text-primary">{n}</p><h2 className="mb-2 text-2xl font-bold">{t}</h2><p className="text-sm leading-relaxed text-muted-foreground">{c}</p></article>)}</div></section></main><SiteFooter/></div>}
