"use client";
type DemoFile={id:string;fileName:string;fileSize:number;downloadCount:number;createdAt:string;expiresAt:string;url:string;sourceDeviceId:string;sourceDeviceName:string};
const demo={files:[] as DemoFile[],pending:new Map<string,{name:string;size:number;deviceId:string}>(),session:null as null|Record<string,unknown>};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
export function installDemoBackend(){if(typeof window==="undefined"||(window as Window&{__drop24Demo?:boolean}).__drop24Demo)return;(window as Window&{__drop24Demo?:boolean}).__drop24Demo=true;const real=window.fetch.bind(window);window.fetch=async(input,init)=>{const raw=typeof input==="string"?input:input instanceof URL?input.href:input.url;const url=new URL(raw,window.location.origin);if(!url.pathname.startsWith("/api/"))return real(input,init);const body=init?.body?JSON.parse(String(init.body)):{};const method=(init?.method||"GET").toUpperCase();
 if(url.pathname==="/api/plan")return json({success:true,plan:"pro",limits:{maxFileBytes:5368709120,storageBytes:26843545600,defaultRetentionDays:1,retentionDays:30,maxPairedDevices:null,maxDownloadsPerFile:100,priorityTransfers:true},usage:{activeFiles:demo.files.length,storageBytes:demo.files.reduce((n,f)=>n+f.fileSize,0)},subscription:null});
 if(url.pathname==="/api/devices")return json({success:true,devices:[{deviceId:body.deviceId||localStorage.getItem("drop24_device_id")||"demo-device",deviceName:body.deviceName||"This browser",isHost:true,lastSeenAt:new Date().toISOString()}]});
 if(url.pathname==="/api/files"&&method==="GET")return json({success:true,files:demo.files});
 if(url.pathname==="/api/files"&&method==="DELETE"){const id=url.searchParams.get("id");demo.files=demo.files.filter(f=>f.id!==id);return json({success:true})}
 if(url.pathname==="/api/files"&&method==="PATCH"){const id=url.searchParams.get("id");const file=demo.files.find(f=>f.id===id);if(file)file.expiresAt=new Date(Date.now()+30*86400000).toISOString();return json({success:true,file})}
 if(url.pathname==="/api/upload-init"){const id=crypto.randomUUID();demo.pending.set(id,{name:body.fileName,size:body.fileSize,deviceId:body.deviceId});return json({success:true,file:{id},upload:{path:id,token:"local-demo",endpoint:""}})}
 if(url.pathname==="/api/upload-complete"){const p=demo.pending.get(body.fileId)!;const now=new Date();const file={id:body.fileId,fileName:p?.name||"Demo file",fileSize:p?.size||0,downloadCount:0,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+86400000).toISOString(),url:`https://drop24.app/f/${body.fileId.slice(0,8)}`,sourceDeviceId:p?.deviceId||"demo",sourceDeviceName:body.deviceName||"This browser"};demo.files.unshift(file);return json({success:true,file})}
 if(url.pathname==="/api/shared-session"){const action=body.action;if(action==="create"){const id=crypto.randomUUID();demo.session={id,hostUserId:"demo-user",isHost:true,inviteToken:id.slice(0,8),hostStorageCap:26843545600,hostStorageUsed:0,hostMaxFileBytes:5368709120,hostMaxDownloadsPerFile:100,hostRetentionDays:30,members:[{userId:"demo-user",displayName:"Aidan",isHost:true}]};return json({success:true,session:demo.session,inviteToken:(demo.session as {inviteToken:string}).inviteToken})}if(action==="end"||action==="leave"){demo.session=null;return json({success:true})}return json({success:true,session:demo.session})}
 if(url.pathname==="/api/account")return json({success:true});
 if(url.pathname.includes("subscription")||url.pathname.includes("checkout"))return json({success:true,plan:"pro"});
 return json({success:true});};}
